name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CODING_USERNAME }}
        password: ${{ secrets.CODING_PASSWORD }}
        registry: deejac-docker.pkg.coding.net
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deejac-docker.pkg.coding.net/zhanyin-ntr/test/genFace:v1
    - name: Docker image push
      run: docker push deejac-docker.pkg.coding.net/zhanyin-ntr/test/genFace:v1
