name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/runpod-worker-comfy:v0.0.1
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker image push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/runpod-worker-comfy:v0.0.1
    - name: Docker image tag
      run: docker tag  ${{ secrets.DOCKERHUB_USERNAME }}/runpod-worker-comfy:v0.0.1  deejac-docker.pkg.coding.net/zhanyin-ntr/test/runpod-worker-comfy:v0.0.1
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CODING_USERNAME }}
        password: ${{ secrets.CODING_PASSWORD }}
        registry: deejac-docker.pkg.coding.net
    - name: Docker image push
      run: docker push deejac-docker.pkg.coding.net/zhanyin-ntr/test/runpod-worker-comfy:v0.0.1





